version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: ride-postgres
    restart: always
    environment:
      POSTGRES_USER: ride_user
      POSTGRES_PASSWORD: ride_password
      POSTGRES_DB: ride_db
    ports:
      - "5433:5432"   # puerto PostgreSQL
    volumes:
      - ride_postgres_data:/var/lib/postgresql/data

volumes:
  ride_postgres_data:
